# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CheckOut24' do
  use_frameworks!

    pod 'WKBridge'
    pod 'Alamofire', '~> 4.7'
    pod 'SwiftyJSON', '~> 4.0'
end

